spring.application.name=ActivityService

server.port=5001

spring.graphql.graphiql.enabled=true
spring.graphql.graphiql.path=/graphiql
spring.graphql.schema.introspection.enabled=true
graphql.introspection.enabled=true

org.springboot.logging.level=DEBUG